name: the 45 minute radio hour
favicon: null
layout_spectrum: 0.6680980210658163
typography_spectrum: 0.14467095839791
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7152378282044083
  lightness: 0.35078297299332917
  saturation: 0.8021413423120975
  rhythmicContrast: 0.5889082490466535
purpose: []
